name: Publish Docker
on: 
  workflow_dispatch:
  push:
    branches: 
      - 'main'
      # - 'staging'
      # - 'dev'
      # - 'hotfix/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@master
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Set tag
        run: sed 's/\//-/g'  <<< "::set-output name=TAG::${{ steps.extract_branch.outputs.branch }}"
        id: tag
      - name: Get tag
        run: echo "The selected tag is ${{ steps.tag.outputs.TAG }}"
      - name: Build and publish image to Quay
        uses: docker/build-push-action@v4
        with:
          path: Dockerfile
          registry: quay.io
          repository: denbicloud/cron-backup
          username: ${{ secrets.QUOAY_USERNAME  }}
          password: ${{ secrets.QUOAY_TOKEN  }}
          tags: ${{ steps.tag.outputs.TAG }}
